language: node_js
node_js:
  - "6"
cache:
  directories:
    - cache
script:
  - if [ ! -e cache/cache_date.txt ]; then echo "Will generate file"; date -u > cache/cache_date.txt; fi;
  - cat cache/cache_date.txt
